// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQUEIBwVYTm6sAiVH4pbXUq1114lU9ucw',
    appId: '1:823594523079:web:0f66d360f36c3b548fe1e2',
    messagingSenderId: '823594523079',
    projectId: 'yatika71311',
    authDomain: 'yatika71311.firebaseapp.com',
    storageBucket: 'yatika71311.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGeBb0KDC1gR-llv5J0pc72Qt--tm4RMI',
    appId: '1:823594523079:android:1935d7ee9f63fda98fe1e2',
    messagingSenderId: '823594523079',
    projectId: 'yatika71311',
    storageBucket: 'yatika71311.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv9_aOS47XGN6GA7jCRRSTQCoybIeOEKk',
    appId: '1:823594523079:ios:4cb78a55665e22fc8fe1e2',
    messagingSenderId: '823594523079',
    projectId: 'yatika71311',
    storageBucket: 'yatika71311.firebasestorage.app',
    iosBundleId: 'com.example.dd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv9_aOS47XGN6GA7jCRRSTQCoybIeOEKk',
    appId: '1:823594523079:ios:4cb78a55665e22fc8fe1e2',
    messagingSenderId: '823594523079',
    projectId: 'yatika71311',
    storageBucket: 'yatika71311.firebasestorage.app',
    iosBundleId: 'com.example.dd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQUEIBwVYTm6sAiVH4pbXUq1114lU9ucw',
    appId: '1:823594523079:web:c8baa3e8dfbf7f2f8fe1e2',
    messagingSenderId: '823594523079',
    projectId: 'yatika71311',
    authDomain: 'yatika71311.firebaseapp.com',
    storageBucket: 'yatika71311.firebasestorage.app',
  );
}
